#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: androidtether <interface>"
    echo
    exit 1
fi


PID=`pgrep dhcpcd`
if [ "$PID" != "" ]; then
    echo "Shutting down dhcpcd..."
    sudo dhcpcd $1 --release
    sleep 1
fi
echo "Bringing interface down..."
sudo ifconfig $1 down 
sleep 1
echo "Setting interface mode to Ad-Hoc..."
sudo iwconfig $1 mode ad-hoc 
sleep 1
echo "Bringing interface up..."
sudo ifconfig $1 up 
sleep 1
echo "Setting ESSID to 'AndroidTether'..."
sudo iwconfig $1 essid "AndroidTether" 
sleep 1
echo "Attempting to connect..."
sudo dhcpcd -d $1
