#!/bin/bash
sudo iwconfig eth1 essid "darkgate"
PID=`ps ax|grep wpa_supplicant|grep -v grep|awk '{ print $1 }'`
sudo kill -9 $PID
PID=`ps ax|grep dhcpcd|grep -v grep|awk '{ print $1 }'`
sudo kill -9 $PID
sudo wpa_supplicant -B -Dwext -i eth1 -c /etc/homewpa.conf
sleep 3
sudo dhcpcd eth1

