#!/usr/bin/env python

import sys

if __name__=="__main__":
    argc = len(sys.argv)
    if argc != 2:
        print ("Usage: %s <pixels>" % sys.argv[0])
        sys.exit(1)
    try:
        px = int(sys.argv[1])
    except Exception, e:
        print ("Use an integer!")
        sys.exit(1)
    print("%d" % ((px/3)*2))
