#!/usr/bin/env python

import sys

if __name__=="__main__":
    argc = len(sys.argv)
    if argc != 2:
        print ("Usage: %s <pixels>" % sys.argv[0])
        sys.exit(1)
    try:
        xdp = int(sys.argv[1])
    except Exception, e:
        print ("Use an integer!")
        sys.exit(1)
    rdp = ((xdp/3)*2)
    ldp = ((xdp/6)*5)
    print("")
    print("DP Calculations")
    print("-------------------------------------")
    print("values dp:\t\t\t %d" % rdp)
    print("values-large dp:\t\t %d" % ldp)
    print("values-xlarge dp:\t\t %d" % xdp)
    print("")
