#!/bin/bash

cd ~/Downloads; wget -O lwjgl-2.8.3.zip http://downloads.sourceforge.net/project/java-game-lib/Official%20Releases/LWJGL%202.8.3/lwjgl-2.8.3.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fjava-game-lib%2Ffiles%2FOfficial%2520Releases%2FLWJGL%25202.8.3%2F&ts=1336277720&use_mirror=softlayer && unzip lwjgl-2.8.3.zip; cd lwjgl-2.8.3 && cp -r native/linux/* ~/.minecraft/bin/natives/; cp jar/lwjgl.jar ~/.minecraft/bin/;cp jar/jinput.jar ~/.minecraft/bin/;cp jar/lwjgl_util.jar ~/.minecraft/bin/
