#!/bin/bash

ADB=`which adb`

if [ "$ADB" == "" ]; then
    echo
    echo "You must have adb in your path!"
    echo
    exit 1
fi

if [ $# -ne 1 ]; then
    echo
    echo "Usage: $0 <update.zip>"
    echo
    exit 1
fi

ZIP="$1"

#adb push "$ZIP" /sdcard/
adb shell echo "--update_package=SDCARD:$ZIP" > /cache/recovery/command
#adb reboot recovery

