#!/bin/bash

if [ $# -ne 1 ]; then
    echo
    echo "Usage: $0 <commit count>"
    echo
    exit 1
fi

function isInt() {
    printf "%d" $1 > /dev/null 2>&1
    return $?
}

if isInt $1; then
    HASHSET=$(git log --pretty=oneline -n $1 | awk '{ print $1 }')
    for HASH in $(echo $HASHSET); do
        git show $HASH | less
    done
else 
    echo "Argument '$1' must be an integer!"
    exit 1
fi

