#!/bin/bash

# test connection
adb shell mount &> /dev/null
if [ "$?" == "1" ]; then
    echo "Failed to connect to device!"
    exit
fi
SYSTEM=$(adb shell mount | grep system)
DEV=$(echo $SYSTEM|awk '{ print $1 }')
MNT=$(echo $SYSTEM|awk '{ print $3 }')
echo adb shell mount -o remount,rw $DEV $MNT

