#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage: $0 <interface> <essid> [wpa_password]"
    exit
fi

ESSID="$1"
PASSWORD="$2"
INTERFACE="$3"

sudo kill -9 `pgrep dhcpcd`
sudo kill -9 `pgrep wpa_supplicant`

sudo iwconfig "$INTERFACE" essid "$ESSID"
sudo wpa_passphrase "$ESSID" "$PASSWORD" > "/tmp/$ESSID.conf"
sudo wpa_supplicant -B -Dwext -i "$INERFACE" -c "/tmp/$ESSID.conf"
sleep 3
sudo dhcpcd eth0
