#!/bin/bash

if [ $# -ne 1 ]; then
    echo
    echo "Wipes data for all applications containing this package name"
    echo
    echo "Usage: $0 <package name>"
    echo
    exit 1
fi

PACKAGE="$1"

ITEMS=$(adb shell pm list packages | grep $PACKAGE | cut -d ':' -f 2 | tr -d "\r" | xargs)

echo "] Wiping application data"
for ITEM in $(echo $ITEMS)
    do
        echo -n "]--> Wiping $ITEM..."
        adb shell pm clear $ITEM
    done
echo "] Done."
