#!/bin/bash

if [ $# -ne 1 ];then
    echo
    echo "Removes all applications found containing the package name"
    echo
    echo "Usage: $0 <package name>"
    echo
    exit 1
fi

PACKAGE="$1"

ITEMS=$(adb shell pm list packages | grep $PACKAGE | cut -d ':' -f 2 | tr -d "\r" | xargs)

echo "] Wiping device of Nom applications"
for ITEM in $(echo $ITEMS)
do
    echo -n "]--> Removing $ITEM..."
    adb uninstall $ITEM
done
echo "] Done."
